// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.controller;

import com.rev.app.entity.Order;
import com.rev.app.dto.OrderRequestDTO;
import com.rev.app.dto.OrderResponseDTO;
import com.rev.app.mapper.OrderMapper;
import com.rev.app.rest.ApiResponse;
import com.rev.app.service.IOrderService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;

@RestController
@RequestMapping("/api/orders")
public class OrderController {
    private final IOrderService iorderService;
    private final OrderMapper orderMapper;
    private final com.rev.app.service.IUserService iuserService;

    @GetMapping("/statuses")
    public ResponseEntity<ApiResponse<java.util.List<String>>> getOrderStatuses() {
        return ResponseEntity.ok(ApiResponse.success(iorderService.getOrderStatuses(), "Order statuses fetched successfully"));
    }

    @PostMapping
    public ResponseEntity<ApiResponse<OrderResponseDTO>> placeOrder(@Valid @RequestBody OrderRequestDTO request) {
        System.out.println("Processing Place Order Request: " + request);
        OrderResponseDTO order = orderMapper.toDto(iorderService.placeOrder(request));
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(order, "Order placed successfully"));
    }

    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse<OrderResponseDTO>> getOrderById(@PathVariable Integer id) {
        Order order = iorderService.getOrderById(id);
        java.util.List<com.rev.app.entity.OrderItem> items = iorderService.getOrderItems(id);
        OrderResponseDTO dto = orderMapper.toDto(order, items);
        return ResponseEntity.ok(ApiResponse.success(dto, "Order fetched successfully"));
    }

    @GetMapping("/user/{userId}")
    public ResponseEntity<ApiResponse<Page<OrderResponseDTO>>> getUserOrders(@PathVariable Integer userId, @RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size);
        Page<OrderResponseDTO> orders = iorderService.getUserOrders(userId, pageable).map(orderMapper::toDto);
        return ResponseEntity.ok(ApiResponse.success(orders, "User orders fetched successfully"));
    }

    @GetMapping("/seller/{sellerId}")
    public ResponseEntity<ApiResponse<Page<OrderResponseDTO>>> getSellerOrders(@PathVariable Integer sellerId, @RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size);
        Page<OrderResponseDTO> orders = iorderService.getSellerOrders(sellerId, pageable).map(orderMapper::toDto);
        return ResponseEntity.ok(ApiResponse.success(orders, "Seller orders fetched successfully"));
    }

    @GetMapping("/{id}/history")
    public ResponseEntity<ApiResponse<java.util.List<com.rev.app.entity.OrderStatusHistory>>> getOrderHistory(@PathVariable Integer id) {
        return ResponseEntity.ok(ApiResponse.success(iorderService.getOrderHistory(id), "Order history fetched successfully"));
    }

    @PatchMapping("/{id}/status")
    public ResponseEntity<ApiResponse<OrderResponseDTO>> updateOrderStatus(@PathVariable Integer id, @RequestParam String status, java.security.Principal principal) {
        if (principal == null) {
            throw new RuntimeException("Authentication required");
        }
        com.rev.app.entity.User currentUser = iuserService.getUserByEmail(principal.getName());
        OrderResponseDTO order = orderMapper.toDto(iorderService.updateOrderStatus(id, status, currentUser.getUserId()));
        return ResponseEntity.ok(ApiResponse.success(order, "Order status updated to " + status));
    }

    @java.lang.SuppressWarnings("all")
    
    public OrderController(final IOrderService iorderService, final OrderMapper orderMapper, final com.rev.app.service.IUserService iuserService) {
        this.iorderService = iorderService;
        this.orderMapper = orderMapper;
        this.iuserService = iuserService;
    }
}
