// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.entity;

import jakarta.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "carts")
public class Cart {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "cart_id")
    private Integer cartId;
    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    
    public static class CartBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Integer cartId;
        @java.lang.SuppressWarnings("all")
        
        private User user;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        CartBuilder() {
        }


        @java.lang.SuppressWarnings("all")
        
        public Cart.CartBuilder cartId(final Integer cartId) {
            this.cartId = cartId;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Cart.CartBuilder user(final User user) {
            this.user = user;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Cart.CartBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Cart build() {
            return new Cart(this.cartId, this.user, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Cart.CartBuilder(cartId=" + this.cartId + ", user=" + this.user + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Cart.CartBuilder builder() {
        return new Cart.CartBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getCartId() {
        return this.cartId;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCartId(final Integer cartId) {
        this.cartId = cartId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Cart)) return false;
        final Cart other = (Cart) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$cartId = this.getCartId();
        final java.lang.Object other$cartId = other.getCartId();
        if (this$cartId == null ? other$cartId != null : !this$cartId.equals(other$cartId)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Cart;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $cartId = this.getCartId();
        result = result * PRIME + ($cartId == null ? 43 : $cartId.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "Cart(cartId=" + this.getCartId() + ", user=" + this.getUser() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public Cart() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Cart(final Integer cartId, final User user, final LocalDateTime createdAt) {
        this.cartId = cartId;
        this.user = user;
        this.createdAt = createdAt;
    }
}
