// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;

@Entity
@Table(name = "order_items")
public class OrderItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "order_item_id")
    private Integer orderItemId;
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;
    @ManyToOne
    @JoinColumn(name = "seller_id")
    private Seller seller;
    @Column(name = "unit_price", precision = 10, scale = 2)
    private BigDecimal unitPrice;
    private Integer quantity;
    @Column(precision = 12, scale = 2)
    private BigDecimal subtotal;


    @java.lang.SuppressWarnings("all")
    
    public static class OrderItemBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Integer orderItemId;
        @java.lang.SuppressWarnings("all")
        
        private Order order;
        @java.lang.SuppressWarnings("all")
        
        private Product product;
        @java.lang.SuppressWarnings("all")
        
        private Seller seller;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal unitPrice;
        @java.lang.SuppressWarnings("all")
        
        private Integer quantity;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal subtotal;

        @java.lang.SuppressWarnings("all")
        
        OrderItemBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder orderItemId(final Integer orderItemId) {
            this.orderItemId = orderItemId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder order(final Order order) {
            this.order = order;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder product(final Product product) {
            this.product = product;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder seller(final Seller seller) {
            this.seller = seller;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder unitPrice(final BigDecimal unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder quantity(final Integer quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OrderItem.OrderItemBuilder subtotal(final BigDecimal subtotal) {
            this.subtotal = subtotal;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public OrderItem build() {
            return new OrderItem(this.orderItemId, this.order, this.product, this.seller, this.unitPrice, this.quantity, this.subtotal);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "OrderItem.OrderItemBuilder(orderItemId=" + this.orderItemId + ", order=" + this.order + ", product=" + this.product + ", seller=" + this.seller + ", unitPrice=" + this.unitPrice + ", quantity=" + this.quantity + ", subtotal=" + this.subtotal + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static OrderItem.OrderItemBuilder builder() {
        return new OrderItem.OrderItemBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getOrderItemId() {
        return this.orderItemId;
    }

    @java.lang.SuppressWarnings("all")
    
    public Order getOrder() {
        return this.order;
    }

    @java.lang.SuppressWarnings("all")
    
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    
    public Seller getSeller() {
        return this.seller;
    }

    @java.lang.SuppressWarnings("all")
    
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setOrderItemId(final Integer orderItemId) {
        this.orderItemId = orderItemId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setOrder(final Order order) {
        this.order = order;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setProduct(final Product product) {
        this.product = product;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setSeller(final Seller seller) {
        this.seller = seller;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUnitPrice(final BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setSubtotal(final BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OrderItem)) return false;
        final OrderItem other = (OrderItem) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$orderItemId = this.getOrderItemId();
        final java.lang.Object other$orderItemId = other.getOrderItemId();
        if (this$orderItemId == null ? other$orderItemId != null : !this$orderItemId.equals(other$orderItemId)) return false;
        final java.lang.Object this$quantity = this.getQuantity();
        final java.lang.Object other$quantity = other.getQuantity();
        if (this$quantity == null ? other$quantity != null : !this$quantity.equals(other$quantity)) return false;
        final java.lang.Object this$order = this.getOrder();
        final java.lang.Object other$order = other.getOrder();
        if (this$order == null ? other$order != null : !this$order.equals(other$order)) return false;
        final java.lang.Object this$product = this.getProduct();
        final java.lang.Object other$product = other.getProduct();
        if (this$product == null ? other$product != null : !this$product.equals(other$product)) return false;
        final java.lang.Object this$seller = this.getSeller();
        final java.lang.Object other$seller = other.getSeller();
        if (this$seller == null ? other$seller != null : !this$seller.equals(other$seller)) return false;
        final java.lang.Object this$unitPrice = this.getUnitPrice();
        final java.lang.Object other$unitPrice = other.getUnitPrice();
        if (this$unitPrice == null ? other$unitPrice != null : !this$unitPrice.equals(other$unitPrice)) return false;
        final java.lang.Object this$subtotal = this.getSubtotal();
        final java.lang.Object other$subtotal = other.getSubtotal();
        if (this$subtotal == null ? other$subtotal != null : !this$subtotal.equals(other$subtotal)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OrderItem;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $orderItemId = this.getOrderItemId();
        result = result * PRIME + ($orderItemId == null ? 43 : $orderItemId.hashCode());
        final java.lang.Object $quantity = this.getQuantity();
        result = result * PRIME + ($quantity == null ? 43 : $quantity.hashCode());
        final java.lang.Object $order = this.getOrder();
        result = result * PRIME + ($order == null ? 43 : $order.hashCode());
        final java.lang.Object $product = this.getProduct();
        result = result * PRIME + ($product == null ? 43 : $product.hashCode());
        final java.lang.Object $seller = this.getSeller();
        result = result * PRIME + ($seller == null ? 43 : $seller.hashCode());
        final java.lang.Object $unitPrice = this.getUnitPrice();
        result = result * PRIME + ($unitPrice == null ? 43 : $unitPrice.hashCode());
        final java.lang.Object $subtotal = this.getSubtotal();
        result = result * PRIME + ($subtotal == null ? 43 : $subtotal.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "OrderItem(orderItemId=" + this.getOrderItemId() + ", order=" + this.getOrder() + ", product=" + this.getProduct() + ", seller=" + this.getSeller() + ", unitPrice=" + this.getUnitPrice() + ", quantity=" + this.getQuantity() + ", subtotal=" + this.getSubtotal() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public OrderItem() {
    }

    @java.lang.SuppressWarnings("all")
    
    public OrderItem(final Integer orderItemId, final Order order, final Product product, final Seller seller, final BigDecimal unitPrice, final Integer quantity, final BigDecimal subtotal) {
        this.orderItemId = orderItemId;
        this.order = order;
        this.product = product;
        this.seller = seller;
        this.unitPrice = unitPrice;
        this.quantity = quantity;
        this.subtotal = subtotal;
    }
}
