// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.entity;

import jakarta.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "password_recovery")
public class PasswordRecovery {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "recovery_id")
    private Integer recoveryId;
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(name = "token", nullable = false, unique = true, length = 255)
    private String token;
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;
    @Column(name = "is_used", nullable = false)
    private Boolean isUsed;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isUsed() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PasswordRecoveryBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Integer recoveryId;
        @java.lang.SuppressWarnings("all")
        
        private User user;
        @java.lang.SuppressWarnings("all")
        
        private String token;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime expiresAt;
        @java.lang.SuppressWarnings("all")
        
        private boolean isUsed$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isUsed$value;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        PasswordRecoveryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery.PasswordRecoveryBuilder recoveryId(final Integer recoveryId) {
            this.recoveryId = recoveryId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery.PasswordRecoveryBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery.PasswordRecoveryBuilder token(final String token) {
            this.token = token;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery.PasswordRecoveryBuilder expiresAt(final LocalDateTime expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery.PasswordRecoveryBuilder isUsed(final Boolean isUsed) {
            this.isUsed$value = isUsed;
            isUsed$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery.PasswordRecoveryBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public PasswordRecovery build() {
            Boolean isUsed$value = this.isUsed$value;
            if (!this.isUsed$set) isUsed$value = PasswordRecovery.$default$isUsed();
            return new PasswordRecovery(this.recoveryId, this.user, this.token, this.expiresAt, isUsed$value, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PasswordRecovery.PasswordRecoveryBuilder(recoveryId=" + this.recoveryId + ", user=" + this.user + ", token=" + this.token + ", expiresAt=" + this.expiresAt + ", isUsed$value=" + this.isUsed$value + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static PasswordRecovery.PasswordRecoveryBuilder builder() {
        return new PasswordRecovery.PasswordRecoveryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getRecoveryId() {
        return this.recoveryId;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getToken() {
        return this.token;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Boolean getIsUsed() {
        return this.isUsed;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRecoveryId(final Integer recoveryId) {
        this.recoveryId = recoveryId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setExpiresAt(final LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setIsUsed(final Boolean isUsed) {
        this.isUsed = isUsed;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PasswordRecovery)) return false;
        final PasswordRecovery other = (PasswordRecovery) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$recoveryId = this.getRecoveryId();
        final java.lang.Object other$recoveryId = other.getRecoveryId();
        if (this$recoveryId == null ? other$recoveryId != null : !this$recoveryId.equals(other$recoveryId)) return false;
        final java.lang.Object this$isUsed = this.getIsUsed();
        final java.lang.Object other$isUsed = other.getIsUsed();
        if (this$isUsed == null ? other$isUsed != null : !this$isUsed.equals(other$isUsed)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$expiresAt = this.getExpiresAt();
        final java.lang.Object other$expiresAt = other.getExpiresAt();
        if (this$expiresAt == null ? other$expiresAt != null : !this$expiresAt.equals(other$expiresAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PasswordRecovery;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $recoveryId = this.getRecoveryId();
        result = result * PRIME + ($recoveryId == null ? 43 : $recoveryId.hashCode());
        final java.lang.Object $isUsed = this.getIsUsed();
        result = result * PRIME + ($isUsed == null ? 43 : $isUsed.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $expiresAt = this.getExpiresAt();
        result = result * PRIME + ($expiresAt == null ? 43 : $expiresAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "PasswordRecovery(recoveryId=" + this.getRecoveryId() + ", user=" + this.getUser() + ", token=" + this.getToken() + ", expiresAt=" + this.getExpiresAt() + ", isUsed=" + this.getIsUsed() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public PasswordRecovery() {
        this.isUsed = PasswordRecovery.$default$isUsed();
    }

    @java.lang.SuppressWarnings("all")
    
    public PasswordRecovery(final Integer recoveryId, final User user, final String token, final LocalDateTime expiresAt, final Boolean isUsed, final LocalDateTime createdAt) {
        this.recoveryId = recoveryId;
        this.user = user;
        this.token = token;
        this.expiresAt = expiresAt;
        this.isUsed = isUsed;
        this.createdAt = createdAt;
    }
}
