// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.entity;

import jakarta.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "products")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "product_id")
    private Integer productId;
    @ManyToOne
    @JoinColumn(name = "seller_id")
    private Seller seller;
    @ManyToOne
    @JoinColumn(name = "category_id")
    private Category category;
    @Column(nullable = false, length = 150)
    private String name;
    @Column(columnDefinition = "CLOB")
    private String description;
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;
    @Column(precision = 10, scale = 2)
    private BigDecimal mrp;
    @Column(name = "discount_price", precision = 10, scale = 2)
    private BigDecimal discountPrice;
    @Column(name = "stock_quantity", nullable = false)
    private Integer stockQuantity;
    @Column(name = "stock_threshold")
    private Integer stockThreshold;
    @Column(name = "is_active")
    private Boolean isActive;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    @Column(name = "image_url", length = 500)
    private String imageUrl;


    @java.lang.SuppressWarnings("all")
    
    public static class ProductBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Integer productId;
        @java.lang.SuppressWarnings("all")
        
        private Seller seller;
        @java.lang.SuppressWarnings("all")
        
        private Category category;
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal price;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal mrp;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal discountPrice;
        @java.lang.SuppressWarnings("all")
        
        private Integer stockQuantity;
        @java.lang.SuppressWarnings("all")
        
        private Integer stockThreshold;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isActive;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime updatedAt;
        @java.lang.SuppressWarnings("all")
        
        private String imageUrl;

        @java.lang.SuppressWarnings("all")
        
        ProductBuilder() {
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder productId(final Integer productId) {
            this.productId = productId;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder seller(final Seller seller) {
            this.seller = seller;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder category(final Category category) {
            this.category = category;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder name(final String name) {
            this.name = name;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder description(final String description) {
            this.description = description;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder price(final BigDecimal price) {
            this.price = price;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder mrp(final BigDecimal mrp) {
            this.mrp = mrp;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder discountPrice(final BigDecimal discountPrice) {
            this.discountPrice = discountPrice;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder stockQuantity(final Integer stockQuantity) {
            this.stockQuantity = stockQuantity;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder stockThreshold(final Integer stockThreshold) {
            this.stockThreshold = stockThreshold;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder isActive(final Boolean isActive) {
            this.isActive = isActive;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Product.ProductBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Product build() {
            return new Product(this.productId, this.seller, this.category, this.name, this.description, this.price, this.mrp, this.discountPrice, this.stockQuantity, this.stockThreshold, this.isActive, this.createdAt, this.updatedAt, this.imageUrl);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Product.ProductBuilder(productId=" + this.productId + ", seller=" + this.seller + ", category=" + this.category + ", name=" + this.name + ", description=" + this.description + ", price=" + this.price + ", mrp=" + this.mrp + ", discountPrice=" + this.discountPrice + ", stockQuantity=" + this.stockQuantity + ", stockThreshold=" + this.stockThreshold + ", isActive=" + this.isActive + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ", imageUrl=" + this.imageUrl + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Product.ProductBuilder builder() {
        return new Product.ProductBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    
    public Seller getSeller() {
        return this.seller;
    }

    @java.lang.SuppressWarnings("all")
    
    public Category getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    
    public BigDecimal getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    
    public BigDecimal getMrp() {
        return this.mrp;
    }

    @java.lang.SuppressWarnings("all")
    
    public BigDecimal getDiscountPrice() {
        return this.discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getStockQuantity() {
        return this.stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getStockThreshold() {
        return this.stockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    
    public Boolean getIsActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setProductId(final Integer productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setSeller(final Seller seller) {
        this.seller = seller;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCategory(final Category category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setMrp(final BigDecimal mrp) {
        this.mrp = mrp;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDiscountPrice(final BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setStockQuantity(final Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setStockThreshold(final Integer stockThreshold) {
        this.stockThreshold = stockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setIsActive(final Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Product)) return false;
        final Product other = (Product) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$productId = this.getProductId();
        final java.lang.Object other$productId = other.getProductId();
        if (this$productId == null ? other$productId != null : !this$productId.equals(other$productId)) return false;
        final java.lang.Object this$stockQuantity = this.getStockQuantity();
        final java.lang.Object other$stockQuantity = other.getStockQuantity();
        if (this$stockQuantity == null ? other$stockQuantity != null : !this$stockQuantity.equals(other$stockQuantity)) return false;
        final java.lang.Object this$stockThreshold = this.getStockThreshold();
        final java.lang.Object other$stockThreshold = other.getStockThreshold();
        if (this$stockThreshold == null ? other$stockThreshold != null : !this$stockThreshold.equals(other$stockThreshold)) return false;
        final java.lang.Object this$isActive = this.getIsActive();
        final java.lang.Object other$isActive = other.getIsActive();
        if (this$isActive == null ? other$isActive != null : !this$isActive.equals(other$isActive)) return false;
        final java.lang.Object this$seller = this.getSeller();
        final java.lang.Object other$seller = other.getSeller();
        if (this$seller == null ? other$seller != null : !this$seller.equals(other$seller)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$price = this.getPrice();
        final java.lang.Object other$price = other.getPrice();
        if (this$price == null ? other$price != null : !this$price.equals(other$price)) return false;
        final java.lang.Object this$mrp = this.getMrp();
        final java.lang.Object other$mrp = other.getMrp();
        if (this$mrp == null ? other$mrp != null : !this$mrp.equals(other$mrp)) return false;
        final java.lang.Object this$discountPrice = this.getDiscountPrice();
        final java.lang.Object other$discountPrice = other.getDiscountPrice();
        if (this$discountPrice == null ? other$discountPrice != null : !this$discountPrice.equals(other$discountPrice)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Product;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $productId = this.getProductId();
        result = result * PRIME + ($productId == null ? 43 : $productId.hashCode());
        final java.lang.Object $stockQuantity = this.getStockQuantity();
        result = result * PRIME + ($stockQuantity == null ? 43 : $stockQuantity.hashCode());
        final java.lang.Object $stockThreshold = this.getStockThreshold();
        result = result * PRIME + ($stockThreshold == null ? 43 : $stockThreshold.hashCode());
        final java.lang.Object $isActive = this.getIsActive();
        result = result * PRIME + ($isActive == null ? 43 : $isActive.hashCode());
        final java.lang.Object $seller = this.getSeller();
        result = result * PRIME + ($seller == null ? 43 : $seller.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $price = this.getPrice();
        result = result * PRIME + ($price == null ? 43 : $price.hashCode());
        final java.lang.Object $mrp = this.getMrp();
        result = result * PRIME + ($mrp == null ? 43 : $mrp.hashCode());
        final java.lang.Object $discountPrice = this.getDiscountPrice();
        result = result * PRIME + ($discountPrice == null ? 43 : $discountPrice.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "Product(productId=" + this.getProductId() + ", seller=" + this.getSeller() + ", category=" + this.getCategory() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", price=" + this.getPrice() + ", mrp=" + this.getMrp() + ", discountPrice=" + this.getDiscountPrice() + ", stockQuantity=" + this.getStockQuantity() + ", stockThreshold=" + this.getStockThreshold() + ", isActive=" + this.getIsActive() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", imageUrl=" + this.getImageUrl() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public Product() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Product(final Integer productId, final Seller seller, final Category category, final String name, final String description, final BigDecimal price, final BigDecimal mrp, final BigDecimal discountPrice, final Integer stockQuantity, final Integer stockThreshold, final Boolean isActive, final LocalDateTime createdAt, final LocalDateTime updatedAt, final String imageUrl) {
        this.productId = productId;
        this.seller = seller;
        this.category = category;
        this.name = name;
        this.description = description;
        this.price = price;
        this.mrp = mrp;
        this.discountPrice = discountPrice;
        this.stockQuantity = stockQuantity;
        this.stockThreshold = stockThreshold;
        this.isActive = isActive;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.imageUrl = imageUrl;
    }
}
