// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.entity;

import jakarta.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "reviews")
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "review_id")
    private Integer reviewId;
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;
    private Integer rating;
    @Lob
    @Column(name = "review_text", columnDefinition = "CLOB")
    private String reviewText;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    
    public static class ReviewBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Integer reviewId;
        @java.lang.SuppressWarnings("all")
        
        private User user;
        @java.lang.SuppressWarnings("all")
        
        private Product product;
        @java.lang.SuppressWarnings("all")
        
        private Integer rating;
        @java.lang.SuppressWarnings("all")
        
        private String reviewText;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        ReviewBuilder() {
        }


        @java.lang.SuppressWarnings("all")
        
        public Review.ReviewBuilder reviewId(final Integer reviewId) {
            this.reviewId = reviewId;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Review.ReviewBuilder user(final User user) {
            this.user = user;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Review.ReviewBuilder product(final Product product) {
            this.product = product;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Review.ReviewBuilder rating(final Integer rating) {
            this.rating = rating;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Review.ReviewBuilder reviewText(final String reviewText) {
            this.reviewText = reviewText;
            return this;
        }


        @java.lang.SuppressWarnings("all")
        
        public Review.ReviewBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Review build() {
            return new Review(this.reviewId, this.user, this.product, this.rating, this.reviewText, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Review.ReviewBuilder(reviewId=" + this.reviewId + ", user=" + this.user + ", product=" + this.product + ", rating=" + this.rating + ", reviewText=" + this.reviewText + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Review.ReviewBuilder builder() {
        return new Review.ReviewBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getReviewId() {
        return this.reviewId;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getReviewText() {
        return this.reviewText;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setReviewId(final Integer reviewId) {
        this.reviewId = reviewId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setProduct(final Product product) {
        this.product = product;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRating(final Integer rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setReviewText(final String reviewText) {
        this.reviewText = reviewText;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Review)) return false;
        final Review other = (Review) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$reviewId = this.getReviewId();
        final java.lang.Object other$reviewId = other.getReviewId();
        if (this$reviewId == null ? other$reviewId != null : !this$reviewId.equals(other$reviewId)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$product = this.getProduct();
        final java.lang.Object other$product = other.getProduct();
        if (this$product == null ? other$product != null : !this$product.equals(other$product)) return false;
        final java.lang.Object this$reviewText = this.getReviewText();
        final java.lang.Object other$reviewText = other.getReviewText();
        if (this$reviewText == null ? other$reviewText != null : !this$reviewText.equals(other$reviewText)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Review;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $reviewId = this.getReviewId();
        result = result * PRIME + ($reviewId == null ? 43 : $reviewId.hashCode());
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $product = this.getProduct();
        result = result * PRIME + ($product == null ? 43 : $product.hashCode());
        final java.lang.Object $reviewText = this.getReviewText();
        result = result * PRIME + ($reviewText == null ? 43 : $reviewText.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "Review(reviewId=" + this.getReviewId() + ", user=" + this.getUser() + ", product=" + this.getProduct() + ", rating=" + this.getRating() + ", reviewText=" + this.getReviewText() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public Review() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Review(final Integer reviewId, final User user, final Product product, final Integer rating, final String reviewText, final LocalDateTime createdAt) {
        this.reviewId = reviewId;
        this.user = user;
        this.product = product;
        this.rating = rating;
        this.reviewText = reviewText;
        this.createdAt = createdAt;
    }
}
