// Generated by delombok at Mon Feb 23 14:36:29 IST 2026
package com.rev.app.entity;

import jakarta.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "sellers")
public class Seller {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "seller_id")
    private Integer sellerId;
    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;
    @Column(name = "business_name", length = 150)
    private String businessName;
    @Column(name = "gst_number", length = 50)
    private String gstNumber;
    @Column(length = 255)
    private String address;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    
    public static class SellerBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Integer sellerId;
        @java.lang.SuppressWarnings("all")
        
        private User user;
        @java.lang.SuppressWarnings("all")
        
        private String businessName;
        @java.lang.SuppressWarnings("all")
        
        private String gstNumber;
        @java.lang.SuppressWarnings("all")
        
        private String address;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        SellerBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Seller.SellerBuilder sellerId(final Integer sellerId) {
            this.sellerId = sellerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Seller.SellerBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Seller.SellerBuilder businessName(final String businessName) {
            this.businessName = businessName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Seller.SellerBuilder gstNumber(final String gstNumber) {
            this.gstNumber = gstNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Seller.SellerBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Seller.SellerBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Seller build() {
            return new Seller(this.sellerId, this.user, this.businessName, this.gstNumber, this.address, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Seller.SellerBuilder(sellerId=" + this.sellerId + ", user=" + this.user + ", businessName=" + this.businessName + ", gstNumber=" + this.gstNumber + ", address=" + this.address + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Seller.SellerBuilder builder() {
        return new Seller.SellerBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getSellerId() {
        return this.sellerId;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getBusinessName() {
        return this.businessName;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getGstNumber() {
        return this.gstNumber;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setSellerId(final Integer sellerId) {
        this.sellerId = sellerId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setBusinessName(final String businessName) {
        this.businessName = businessName;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setGstNumber(final String gstNumber) {
        this.gstNumber = gstNumber;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Seller)) return false;
        final Seller other = (Seller) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sellerId = this.getSellerId();
        final java.lang.Object other$sellerId = other.getSellerId();
        if (this$sellerId == null ? other$sellerId != null : !this$sellerId.equals(other$sellerId)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$businessName = this.getBusinessName();
        final java.lang.Object other$businessName = other.getBusinessName();
        if (this$businessName == null ? other$businessName != null : !this$businessName.equals(other$businessName)) return false;
        final java.lang.Object this$gstNumber = this.getGstNumber();
        final java.lang.Object other$gstNumber = other.getGstNumber();
        if (this$gstNumber == null ? other$gstNumber != null : !this$gstNumber.equals(other$gstNumber)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Seller;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sellerId = this.getSellerId();
        result = result * PRIME + ($sellerId == null ? 43 : $sellerId.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $businessName = this.getBusinessName();
        result = result * PRIME + ($businessName == null ? 43 : $businessName.hashCode());
        final java.lang.Object $gstNumber = this.getGstNumber();
        result = result * PRIME + ($gstNumber == null ? 43 : $gstNumber.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "Seller(sellerId=" + this.getSellerId() + ", user=" + this.getUser() + ", businessName=" + this.getBusinessName() + ", gstNumber=" + this.getGstNumber() + ", address=" + this.getAddress() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public Seller() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Seller(final Integer sellerId, final User user, final String businessName, final String gstNumber, final String address, final LocalDateTime createdAt) {
        this.sellerId = sellerId;
        this.user = user;
        this.businessName = businessName;
        this.gstNumber = gstNumber;
        this.address = address;
        this.createdAt = createdAt;
    }
}
